env : "production"
database :
  local :
    host : '127.0.0.1'
    user : 'root'
    password : ''
    database : 'test1'
    port : 3306
  mongo :
    host : '127.0.0.1'
    database : 'iData'
    collection : 'test'
    entity : 'topEntity'
    port : 27017
